
# defines name of github action
name: Node.js CI

# defines which github action this file will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # defines which operating system will it run
    runs-on: ubuntu-latest
    
    
    strategy:
      matrix:
        node-version: [16.x]

    # defines steps on how will this github actions behaves when it's running
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

